/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  uuid,
  varchar,
  timestamp,
  boolean,
  numeric,
  serial,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_admin_role = pgEnum("enum_admin_role", ["admin"]);
export const enum_icon_name = pgEnum("enum_icon_name", [
  "arrowRight",
  "bank",
  "bolt",
  "briefcase",
  "bus",
  "check",
  "chevronDown",
  "chevronRight",
  "city",
  "close",
  "compass",
  "document",
  "download",
  "drain",
  "droplet",
  "external",
  "facebook",
  "fence",
  "hospital",
  "instagram",
  "key",
  "lamp",
  "mail",
  "mapPin",
  "menu",
  "phone",
  "plane",
  "road",
  "route",
  "ruler",
  "school",
  "shield",
  "shop",
  "star",
  "temple",
  "train",
  "tree",
  "wall",
  "whatsapp",
  "youtube",
  "zoomIn",
]);
export const enum_project_category = pgEnum("enum_project_category", [
  "Premium Villa Plots",
  "Farm Villa Plots",
  "Residential Plots",
  "Apartments",
]);
export const enum_project_status = pgEnum("enum_project_status", [
  "Open for booking",
  "Nearing sell-out",
  "Completed",
  "Coming soon",
]);
export const enum_projects_status = pgEnum("enum_projects_status", [
  "draft",
  "published",
]);
export const enum__projects_v_version_status = pgEnum(
  "enum__projects_v_version_status",
  ["draft", "published"],
);
export const enum_lead_source = pgEnum("enum_lead_source", [
  "contact_form",
  "hero_pill",
  "whatsapp",
  "phone",
]);
export const enum_testimonials_status = pgEnum("enum_testimonials_status", [
  "draft",
  "published",
]);
export const enum__testimonials_v_version_status = pgEnum(
  "enum__testimonials_v_version_status",
  ["draft", "published"],
);
export const enum_faqs_status = pgEnum("enum_faqs_status", [
  "draft",
  "published",
]);
export const enum__faqs_v_version_status = pgEnum(
  "enum__faqs_v_version_status",
  ["draft", "published"],
);
export const enum_statistics_status = pgEnum("enum_statistics_status", [
  "draft",
  "published",
]);
export const enum__statistics_v_version_status = pgEnum(
  "enum__statistics_v_version_status",
  ["draft", "published"],
);
export const enum_audit_action = pgEnum("enum_audit_action", [
  "create",
  "update",
  "publish",
  "unpublish",
  "delete",
  "restore",
  "login",
  "logout",
  "login_failed",
  "lockout",
  "password_change",
]);
export const enum_payload_jobs_log_task_slug = pgEnum(
  "enum_payload_jobs_log_task_slug",
  [
    "inline",
    "sendLeadNotification",
    "revalidatePaths",
    "purgeLeadPii",
    "sweepDeletedMedia",
    "watchdogFailedJobs",
  ],
);
export const enum_payload_jobs_log_state = pgEnum(
  "enum_payload_jobs_log_state",
  ["failed", "succeeded"],
);
export const enum_payload_jobs_task_slug = pgEnum(
  "enum_payload_jobs_task_slug",
  [
    "inline",
    "sendLeadNotification",
    "revalidatePaths",
    "purgeLeadPii",
    "sweepDeletedMedia",
    "watchdogFailedJobs",
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    password: varchar("password"),
    name: varchar("name").notNull(),
    role: enum_admin_role("role").notNull().default("admin"),
    isActive: boolean("is_active").notNull().default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    resetPasswordRequestedAt: timestamp("reset_password_requested_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    alt: varchar("alt").notNull(),
    isDecorative: boolean("is_decorative").default(false),
    originalFilename: varchar("original_filename"),
    uploadedBy: uuid("uploaded_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    prefix: varchar("prefix").default("media"),
    _objectKey: varchar("_objectkey"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
  },
  (columns) => [
    index("media_uploaded_by_idx").on(columns.uploadedBy),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    index("media_deleted_at_idx").on(columns.deletedAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
  ],
);

export const media_texts = pgTable(
  "media_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("media_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [media.id],
      name: "media_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const documents = pgTable(
  "documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    title: varchar("title").notNull(),
    originalFilename: varchar("original_filename"),
    uploadedBy: uuid("uploaded_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    prefix: varchar("prefix").default("documents"),
    _objectKey: varchar("_objectkey"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
  },
  (columns) => [
    index("documents_uploaded_by_idx").on(columns.uploadedBy),
    index("documents_updated_at_idx").on(columns.updatedAt),
    index("documents_created_at_idx").on(columns.createdAt),
    index("documents_deleted_at_idx").on(columns.deletedAt),
    uniqueIndex("documents_filename_idx").on(columns.filename),
  ],
);

export const documents_texts = pgTable(
  "documents_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("documents_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [documents.id],
      name: "documents_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_stats = pgTable(
  "proj_stats",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label"),
    value: varchar("value"),
  },
  (columns) => [
    index("proj_stats_order_idx").on(columns._order),
    index("proj_stats_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_stats_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_highlights = pgTable(
  "proj_highlights",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
  },
  (columns) => [
    index("proj_highlights_order_idx").on(columns._order),
    index("proj_highlights_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_highlights_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_approvals = pgTable(
  "proj_approvals",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
  },
  (columns) => [
    index("proj_approvals_order_idx").on(columns._order),
    index("proj_approvals_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_approvals_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_amenities = pgTable(
  "proj_amenities",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
  },
  (columns) => [
    index("proj_amenities_order_idx").on(columns._order),
    index("proj_amenities_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_amenities_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_loc_hl = pgTable(
  "proj_loc_hl",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
  },
  (columns) => [
    index("proj_loc_hl_order_idx").on(columns._order),
    index("proj_loc_hl_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_loc_hl_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const proj_proximity = pgTable(
  "proj_proximity",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon"),
    measure: varchar("measure"),
    place: varchar("place"),
  },
  (columns) => [
    index("proj_proximity_order_idx").on(columns._order),
    index("proj_proximity_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "proj_proximity_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    _order: varchar("_order"),
    name: varchar("name"),
    category: enum_project_category("category"),
    projectStatus: enum_project_status("project_status"),
    locality: varchar("locality"),
    developer: varchar("developer"),
    tagline: varchar("tagline"),
    summary: varchar("summary"),
    area: varchar("area"),
    roadDetails: varchar("road_details"),
    image: uuid("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    layoutImage: uuid("layout_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    locationMap: uuid("location_map_id").references(() => media.id, {
      onDelete: "set null",
    }),
    cta_title: varchar("cta_title"),
    cta_description: varchar("cta_description"),
    seo_title: varchar("seo_title"),
    seo_description: varchar("seo_description"),
    slug: varchar("slug"),
    featured: boolean("featured").default(false),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_projects_status("_status").default("draft"),
  },
  (columns) => [
    index("projects__order_idx").on(columns._order),
    index("projects_category_idx").on(columns.category),
    index("projects_image_idx").on(columns.image),
    index("projects_layout_image_idx").on(columns.layoutImage),
    index("projects_location_map_idx").on(columns.locationMap),
    uniqueIndex("projects_slug_idx").on(columns.slug),
    index("projects_featured_idx").on(columns.featured),
    index("projects_updated_at_idx").on(columns.updatedAt),
    index("projects_created_at_idx").on(columns.createdAt),
    index("projects_deleted_at_idx").on(columns.deletedAt),
    index("projects__status_idx").on(columns._status),
  ],
);

export const projects_texts = pgTable(
  "projects_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("projects_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [projects.id],
      name: "projects_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const projects_rels = pgTable(
  "projects_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
  },
  (columns) => [
    index("projects_rels_order_idx").on(columns.order),
    index("projects_rels_parent_idx").on(columns.parent),
    index("projects_rels_path_idx").on(columns.path),
    index("projects_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [projects.id],
      name: "projects_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "projects_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_stats_v = pgTable(
  "_proj_stats_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    label: varchar("label"),
    value: varchar("value"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_stats_v_order_idx").on(columns._order),
    index("_proj_stats_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_stats_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_highlights_v = pgTable(
  "_proj_highlights_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_highlights_v_order_idx").on(columns._order),
    index("_proj_highlights_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_highlights_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_approvals_v = pgTable(
  "_proj_approvals_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_approvals_v_order_idx").on(columns._order),
    index("_proj_approvals_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_approvals_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_amenities_v = pgTable(
  "_proj_amenities_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_amenities_v_order_idx").on(columns._order),
    index("_proj_amenities_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_amenities_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_loc_hl_v = pgTable(
  "_proj_loc_hl_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon"),
    title: varchar("title"),
    body: varchar("body"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_loc_hl_v_order_idx").on(columns._order),
    index("_proj_loc_hl_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_loc_hl_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _proj_proximity_v = pgTable(
  "_proj_proximity_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon"),
    measure: varchar("measure"),
    place: varchar("place"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_proj_proximity_v_order_idx").on(columns._order),
    index("_proj_proximity_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_projects_v.id],
      name: "_proj_proximity_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _projects_v = pgTable(
  "_projects_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => projects.id, {
      onDelete: "set null",
    }),
    version__order: varchar("version__order"),
    version_name: varchar("version_name"),
    version_category: enum_project_category("version_category"),
    version_projectStatus: enum_project_status("version_project_status"),
    version_locality: varchar("version_locality"),
    version_developer: varchar("version_developer"),
    version_tagline: varchar("version_tagline"),
    version_summary: varchar("version_summary"),
    version_area: varchar("version_area"),
    version_roadDetails: varchar("version_road_details"),
    version_image: uuid("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_layoutImage: uuid("version_layout_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_locationMap: uuid("version_location_map_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_cta_title: varchar("version_cta_title"),
    version_cta_description: varchar("version_cta_description"),
    version_seo_title: varchar("version_seo_title"),
    version_seo_description: varchar("version_seo_description"),
    version_slug: varchar("version_slug"),
    version_featured: boolean("version_featured").default(false),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__projects_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_projects_v_parent_idx").on(columns.parent),
    index("_projects_v_version_version__order_idx").on(columns.version__order),
    index("_projects_v_version_version_category_idx").on(
      columns.version_category,
    ),
    index("_projects_v_version_version_image_idx").on(columns.version_image),
    index("_projects_v_version_version_layout_image_idx").on(
      columns.version_layoutImage,
    ),
    index("_projects_v_version_version_location_map_idx").on(
      columns.version_locationMap,
    ),
    index("_projects_v_version_version_slug_idx").on(columns.version_slug),
    index("_projects_v_version_version_featured_idx").on(
      columns.version_featured,
    ),
    index("_projects_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_projects_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_projects_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_projects_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_projects_v_created_at_idx").on(columns.createdAt),
    index("_projects_v_updated_at_idx").on(columns.updatedAt),
    index("_projects_v_latest_idx").on(columns.latest),
  ],
);

export const _projects_v_texts = pgTable(
  "_projects_v_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("_projects_v_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_projects_v.id],
      name: "_projects_v_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const _projects_v_rels = pgTable(
  "_projects_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
  },
  (columns) => [
    index("_projects_v_rels_order_idx").on(columns.order),
    index("_projects_v_rels_parent_idx").on(columns.parent),
    index("_projects_v_rels_path_idx").on(columns.path),
    index("_projects_v_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_projects_v.id],
      name: "_projects_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "_projects_v_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const leads = pgTable(
  "leads",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    phone: varchar("phone").notNull(),
    phoneNormalised: varchar("phone_normalised"),
    projectSlug: varchar("project_slug"),
    project: uuid("project_id").references(() => projects.id, {
      onDelete: "set null",
    }),
    projectNameSnapshot: varchar("project_name_snapshot"),
    message: varchar("message"),
    source: enum_lead_source("source").notNull().default("contact_form"),
    sourcePath: varchar("source_path"),
    notifiedAt: timestamp("notified_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    consentGiven: boolean("consent_given").notNull().default(true),
    isRead: boolean("is_read").default(false),
    ipAddress: varchar("ip_address"),
    userAgent: varchar("user_agent"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("leads_phone_normalised_idx").on(columns.phoneNormalised),
    index("leads_project_slug_idx").on(columns.projectSlug),
    index("leads_project_idx").on(columns.project),
    index("leads_is_read_idx").on(columns.isRead),
    index("leads_updated_at_idx").on(columns.updatedAt),
    index("leads_created_at_idx").on(columns.createdAt),
    index("leads_deleted_at_idx").on(columns.deletedAt),
    index("phoneNormalised_projectSlug_idx").on(
      columns.phoneNormalised,
      columns.projectSlug,
    ),
  ],
);

export const testimonials = pgTable(
  "testimonials",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    _order: varchar("_order"),
    name: varchar("name"),
    role: varchar("role"),
    body: varchar("body"),
    rating: numeric("rating", { mode: "number" }),
    consented: boolean("consented").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_testimonials_status("_status").default("draft"),
  },
  (columns) => [
    index("testimonials__order_idx").on(columns._order),
    index("testimonials_updated_at_idx").on(columns.updatedAt),
    index("testimonials_created_at_idx").on(columns.createdAt),
    index("testimonials_deleted_at_idx").on(columns.deletedAt),
    index("testimonials__status_idx").on(columns._status),
  ],
);

export const _testimonials_v = pgTable(
  "_testimonials_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => testimonials.id, {
      onDelete: "set null",
    }),
    version__order: varchar("version__order"),
    version_name: varchar("version_name"),
    version_role: varchar("version_role"),
    version_body: varchar("version_body"),
    version_rating: numeric("version_rating", { mode: "number" }),
    version_consented: boolean("version_consented").default(false),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__testimonials_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_testimonials_v_parent_idx").on(columns.parent),
    index("_testimonials_v_version_version__order_idx").on(
      columns.version__order,
    ),
    index("_testimonials_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_testimonials_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_testimonials_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_testimonials_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_testimonials_v_created_at_idx").on(columns.createdAt),
    index("_testimonials_v_updated_at_idx").on(columns.updatedAt),
    index("_testimonials_v_latest_idx").on(columns.latest),
  ],
);

export const faqs = pgTable(
  "faqs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    _order: varchar("_order"),
    question: varchar("question"),
    answer: varchar("answer"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_faqs_status("_status").default("draft"),
  },
  (columns) => [
    index("faqs__order_idx").on(columns._order),
    uniqueIndex("faqs_question_idx").on(columns.question),
    index("faqs_updated_at_idx").on(columns.updatedAt),
    index("faqs_created_at_idx").on(columns.createdAt),
    index("faqs_deleted_at_idx").on(columns.deletedAt),
    index("faqs__status_idx").on(columns._status),
  ],
);

export const _faqs_v = pgTable(
  "_faqs_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => faqs.id, {
      onDelete: "set null",
    }),
    version__order: varchar("version__order"),
    version_question: varchar("version_question"),
    version_answer: varchar("version_answer"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__faqs_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_faqs_v_parent_idx").on(columns.parent),
    index("_faqs_v_version_version__order_idx").on(columns.version__order),
    index("_faqs_v_version_version_question_idx").on(columns.version_question),
    index("_faqs_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_faqs_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_faqs_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_faqs_v_version_version__status_idx").on(columns.version__status),
    index("_faqs_v_created_at_idx").on(columns.createdAt),
    index("_faqs_v_updated_at_idx").on(columns.updatedAt),
    index("_faqs_v_latest_idx").on(columns.latest),
  ],
);

export const statistics = pgTable(
  "statistics",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    _order: varchar("_order"),
    label: varchar("label"),
    value: varchar("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_statistics_status("_status").default("draft"),
  },
  (columns) => [
    index("statistics__order_idx").on(columns._order),
    uniqueIndex("statistics_label_idx").on(columns.label),
    index("statistics_updated_at_idx").on(columns.updatedAt),
    index("statistics_created_at_idx").on(columns.createdAt),
    index("statistics_deleted_at_idx").on(columns.deletedAt),
    index("statistics__status_idx").on(columns._status),
  ],
);

export const _statistics_v = pgTable(
  "_statistics_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => statistics.id, {
      onDelete: "set null",
    }),
    version__order: varchar("version__order"),
    version_label: varchar("version_label"),
    version_value: varchar("version_value"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__statistics_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_statistics_v_parent_idx").on(columns.parent),
    index("_statistics_v_version_version__order_idx").on(
      columns.version__order,
    ),
    index("_statistics_v_version_version_label_idx").on(columns.version_label),
    index("_statistics_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_statistics_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_statistics_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_statistics_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_statistics_v_created_at_idx").on(columns.createdAt),
    index("_statistics_v_updated_at_idx").on(columns.updatedAt),
    index("_statistics_v_latest_idx").on(columns.latest),
  ],
);

export const audit_log = pgTable(
  "audit_log",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    adminUser: uuid("admin_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    action: enum_audit_action("action").notNull(),
    entityType: varchar("entity_type").notNull(),
    entityId: varchar("entity_id").notNull(),
    changes: jsonb("changes"),
    ipAddress: varchar("ip_address"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("audit_log_admin_user_idx").on(columns.adminUser),
    index("audit_log_entity_type_idx").on(columns.entityType),
    index("audit_log_entity_id_idx").on(columns.entityId),
    index("audit_log_updated_at_idx").on(columns.updatedAt),
    index("audit_log_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_jobs_log = pgTable(
  "payload_jobs_log",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    executedAt: timestamp("executed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug("task_slug").notNull(),
    taskID: varchar("task_i_d").notNull(),
    input: jsonb("input"),
    output: jsonb("output"),
    state: enum_payload_jobs_log_state("state").notNull(),
    error: jsonb("error"),
  },
  (columns) => [
    index("payload_jobs_log_order_idx").on(columns._order),
    index("payload_jobs_log_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_jobs_log_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_jobs = pgTable(
  "payload_jobs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    input: jsonb("input"),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    totalTried: numeric("total_tried", { mode: "number" }).default(0),
    hasError: boolean("has_error").default(false),
    error: jsonb("error"),
    taskSlug: enum_payload_jobs_task_slug("task_slug"),
    queue: varchar("queue").default("default"),
    waitUntil: timestamp("wait_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    processing: boolean("processing").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_jobs_completed_at_idx").on(columns.completedAt),
    index("payload_jobs_total_tried_idx").on(columns.totalTried),
    index("payload_jobs_has_error_idx").on(columns.hasError),
    index("payload_jobs_task_slug_idx").on(columns.taskSlug),
    index("payload_jobs_queue_idx").on(columns.queue),
    index("payload_jobs_wait_until_idx").on(columns.waitUntil),
    index("payload_jobs_processing_idx").on(columns.processing),
    index("payload_jobs_updated_at_idx").on(columns.updatedAt),
    index("payload_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    mediaID: uuid("media_id"),
    documentsID: uuid("documents_id"),
    projectsID: uuid("projects_id"),
    leadsID: uuid("leads_id"),
    testimonialsID: uuid("testimonials_id"),
    faqsID: uuid("faqs_id"),
    statisticsID: uuid("statistics_id"),
    "audit-logID": uuid("audit_log_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_documents_id_idx").on(
      columns.documentsID,
    ),
    index("payload_locked_documents_rels_projects_id_idx").on(
      columns.projectsID,
    ),
    index("payload_locked_documents_rels_leads_id_idx").on(columns.leadsID),
    index("payload_locked_documents_rels_testimonials_id_idx").on(
      columns.testimonialsID,
    ),
    index("payload_locked_documents_rels_faqs_id_idx").on(columns.faqsID),
    index("payload_locked_documents_rels_statistics_id_idx").on(
      columns.statisticsID,
    ),
    index("payload_locked_documents_rels_audit_log_id_idx").on(
      columns["audit-logID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["documentsID"]],
      foreignColumns: [documents.id],
      name: "payload_locked_documents_rels_documents_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["leadsID"]],
      foreignColumns: [leads.id],
      name: "payload_locked_documents_rels_leads_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["testimonialsID"]],
      foreignColumns: [testimonials.id],
      name: "payload_locked_documents_rels_testimonials_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["faqsID"]],
      foreignColumns: [faqs.id],
      name: "payload_locked_documents_rels_faqs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["statisticsID"]],
      foreignColumns: [statistics.id],
      name: "payload_locked_documents_rels_statistics_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["audit-logID"]],
      foreignColumns: [audit_log.id],
      name: "payload_locked_documents_rels_audit_log_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_social = pgTable(
  "site_social",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    href: varchar("href").notNull(),
    icon: enum_icon_name("icon").notNull(),
  },
  (columns) => [
    index("site_social_order_idx").on(columns._order),
    index("site_social_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_social_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_legal_links = pgTable(
  "site_legal_links",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    href: varchar("href").notNull(),
  },
  (columns) => [
    index("site_legal_links_order_idx").on(columns._order),
    index("site_legal_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_legal_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_hero_ticker = pgTable(
  "site_hero_ticker",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_icon_name("icon").notNull(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("site_hero_ticker_order_idx").on(columns._order),
    index("site_hero_ticker_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_hero_ticker_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    legalName: varchar("legal_name").notNull(),
    tagline: varchar("tagline"),
    description: varchar("description"),
    url: varchar("url").notNull(),
    logo: uuid("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: varchar("email").notNull(),
    phone: varchar("phone").notNull(),
    whatsapp: varchar("whatsapp").notNull(),
    mapUrl: varchar("map_url"),
    officeHours: varchar("office_hours"),
    formNote: varchar("form_note"),
    cta_title: varchar("cta_title"),
    cta_body: varchar("cta_body"),
    masterPlan: uuid("master_plan_id").references(() => documents.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("site_settings_logo_idx").on(columns.logo),
    index("site_settings_master_plan_idx").on(columns.masterPlan),
  ],
);

export const site_settings_texts = pgTable(
  "site_settings_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("site_settings_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const _site_social_v = pgTable(
  "_site_social_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    label: varchar("label").notNull(),
    href: varchar("href").notNull(),
    icon: enum_icon_name("icon").notNull(),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_site_social_v_order_idx").on(columns._order),
    index("_site_social_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_site_settings_v.id],
      name: "_site_social_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _site_legal_links_v = pgTable(
  "_site_legal_links_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    label: varchar("label").notNull(),
    href: varchar("href").notNull(),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_site_legal_links_v_order_idx").on(columns._order),
    index("_site_legal_links_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_site_settings_v.id],
      name: "_site_legal_links_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _site_hero_ticker_v = pgTable(
  "_site_hero_ticker_v",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    icon: enum_icon_name("icon").notNull(),
    text: varchar("text").notNull(),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_site_hero_ticker_v_order_idx").on(columns._order),
    index("_site_hero_ticker_v_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_site_settings_v.id],
      name: "_site_hero_ticker_v_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _site_settings_v = pgTable(
  "_site_settings_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    version_name: varchar("version_name").notNull(),
    version_legalName: varchar("version_legal_name").notNull(),
    version_tagline: varchar("version_tagline"),
    version_description: varchar("version_description"),
    version_url: varchar("version_url").notNull(),
    version_logo: uuid("version_logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_email: varchar("version_email").notNull(),
    version_phone: varchar("version_phone").notNull(),
    version_whatsapp: varchar("version_whatsapp").notNull(),
    version_mapUrl: varchar("version_map_url"),
    version_officeHours: varchar("version_office_hours"),
    version_formNote: varchar("version_form_note"),
    version_cta_title: varchar("version_cta_title"),
    version_cta_body: varchar("version_cta_body"),
    version_masterPlan: uuid("version_master_plan_id").references(
      () => documents.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("_site_settings_v_version_version_logo_idx").on(columns.version_logo),
    index("_site_settings_v_version_version_master_plan_idx").on(
      columns.version_masterPlan,
    ),
    index("_site_settings_v_created_at_idx").on(columns.createdAt),
    index("_site_settings_v_updated_at_idx").on(columns.updatedAt),
  ],
);

export const _site_settings_v_texts = pgTable(
  "_site_settings_v_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("_site_settings_v_texts_order_parent").on(
      columns.order,
      columns.parent,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_site_settings_v.id],
      name: "_site_settings_v_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media_texts = relations(media_texts, ({ one }) => ({
  parent: one(media, {
    fields: [media_texts.parent],
    references: [media.id],
    relationName: "_texts",
  }),
}));
export const relations_media = relations(media, ({ one, many }) => ({
  uploadedBy: one(users, {
    fields: [media.uploadedBy],
    references: [users.id],
    relationName: "uploadedBy",
  }),
  _texts: many(media_texts, {
    relationName: "_texts",
  }),
}));
export const relations_documents_texts = relations(
  documents_texts,
  ({ one }) => ({
    parent: one(documents, {
      fields: [documents_texts.parent],
      references: [documents.id],
      relationName: "_texts",
    }),
  }),
);
export const relations_documents = relations(documents, ({ one, many }) => ({
  uploadedBy: one(users, {
    fields: [documents.uploadedBy],
    references: [users.id],
    relationName: "uploadedBy",
  }),
  _texts: many(documents_texts, {
    relationName: "_texts",
  }),
}));
export const relations_proj_stats = relations(proj_stats, ({ one }) => ({
  _parentID: one(projects, {
    fields: [proj_stats._parentID],
    references: [projects.id],
    relationName: "stats",
  }),
}));
export const relations_proj_highlights = relations(
  proj_highlights,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [proj_highlights._parentID],
      references: [projects.id],
      relationName: "highlights",
    }),
  }),
);
export const relations_proj_approvals = relations(
  proj_approvals,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [proj_approvals._parentID],
      references: [projects.id],
      relationName: "approvals",
    }),
  }),
);
export const relations_proj_amenities = relations(
  proj_amenities,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [proj_amenities._parentID],
      references: [projects.id],
      relationName: "amenities",
    }),
  }),
);
export const relations_proj_loc_hl = relations(proj_loc_hl, ({ one }) => ({
  _parentID: one(projects, {
    fields: [proj_loc_hl._parentID],
    references: [projects.id],
    relationName: "locationHighlights",
  }),
}));
export const relations_proj_proximity = relations(
  proj_proximity,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [proj_proximity._parentID],
      references: [projects.id],
      relationName: "proximity",
    }),
  }),
);
export const relations_projects_texts = relations(
  projects_texts,
  ({ one }) => ({
    parent: one(projects, {
      fields: [projects_texts.parent],
      references: [projects.id],
      relationName: "_texts",
    }),
  }),
);
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [projects_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_projects = relations(projects, ({ one, many }) => ({
  stats: many(proj_stats, {
    relationName: "stats",
  }),
  highlights: many(proj_highlights, {
    relationName: "highlights",
  }),
  approvals: many(proj_approvals, {
    relationName: "approvals",
  }),
  amenities: many(proj_amenities, {
    relationName: "amenities",
  }),
  locationHighlights: many(proj_loc_hl, {
    relationName: "locationHighlights",
  }),
  proximity: many(proj_proximity, {
    relationName: "proximity",
  }),
  image: one(media, {
    fields: [projects.image],
    references: [media.id],
    relationName: "image",
  }),
  layoutImage: one(media, {
    fields: [projects.layoutImage],
    references: [media.id],
    relationName: "layoutImage",
  }),
  locationMap: one(media, {
    fields: [projects.locationMap],
    references: [media.id],
    relationName: "locationMap",
  }),
  _texts: many(projects_texts, {
    relationName: "_texts",
  }),
  _rels: many(projects_rels, {
    relationName: "_rels",
  }),
}));
export const relations__proj_stats_v = relations(_proj_stats_v, ({ one }) => ({
  _parentID: one(_projects_v, {
    fields: [_proj_stats_v._parentID],
    references: [_projects_v.id],
    relationName: "version_stats",
  }),
}));
export const relations__proj_highlights_v = relations(
  _proj_highlights_v,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_proj_highlights_v._parentID],
      references: [_projects_v.id],
      relationName: "version_highlights",
    }),
  }),
);
export const relations__proj_approvals_v = relations(
  _proj_approvals_v,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_proj_approvals_v._parentID],
      references: [_projects_v.id],
      relationName: "version_approvals",
    }),
  }),
);
export const relations__proj_amenities_v = relations(
  _proj_amenities_v,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_proj_amenities_v._parentID],
      references: [_projects_v.id],
      relationName: "version_amenities",
    }),
  }),
);
export const relations__proj_loc_hl_v = relations(
  _proj_loc_hl_v,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_proj_loc_hl_v._parentID],
      references: [_projects_v.id],
      relationName: "version_locationHighlights",
    }),
  }),
);
export const relations__proj_proximity_v = relations(
  _proj_proximity_v,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_proj_proximity_v._parentID],
      references: [_projects_v.id],
      relationName: "version_proximity",
    }),
  }),
);
export const relations__projects_v_texts = relations(
  _projects_v_texts,
  ({ one }) => ({
    parent: one(_projects_v, {
      fields: [_projects_v_texts.parent],
      references: [_projects_v.id],
      relationName: "_texts",
    }),
  }),
);
export const relations__projects_v_rels = relations(
  _projects_v_rels,
  ({ one }) => ({
    parent: one(_projects_v, {
      fields: [_projects_v_rels.parent],
      references: [_projects_v.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [_projects_v_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations__projects_v = relations(
  _projects_v,
  ({ one, many }) => ({
    parent: one(projects, {
      fields: [_projects_v.parent],
      references: [projects.id],
      relationName: "parent",
    }),
    version_stats: many(_proj_stats_v, {
      relationName: "version_stats",
    }),
    version_highlights: many(_proj_highlights_v, {
      relationName: "version_highlights",
    }),
    version_approvals: many(_proj_approvals_v, {
      relationName: "version_approvals",
    }),
    version_amenities: many(_proj_amenities_v, {
      relationName: "version_amenities",
    }),
    version_locationHighlights: many(_proj_loc_hl_v, {
      relationName: "version_locationHighlights",
    }),
    version_proximity: many(_proj_proximity_v, {
      relationName: "version_proximity",
    }),
    version_image: one(media, {
      fields: [_projects_v.version_image],
      references: [media.id],
      relationName: "version_image",
    }),
    version_layoutImage: one(media, {
      fields: [_projects_v.version_layoutImage],
      references: [media.id],
      relationName: "version_layoutImage",
    }),
    version_locationMap: one(media, {
      fields: [_projects_v.version_locationMap],
      references: [media.id],
      relationName: "version_locationMap",
    }),
    _texts: many(_projects_v_texts, {
      relationName: "_texts",
    }),
    _rels: many(_projects_v_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_leads = relations(leads, ({ one }) => ({
  project: one(projects, {
    fields: [leads.project],
    references: [projects.id],
    relationName: "project",
  }),
}));
export const relations_testimonials = relations(testimonials, () => ({}));
export const relations__testimonials_v = relations(
  _testimonials_v,
  ({ one }) => ({
    parent: one(testimonials, {
      fields: [_testimonials_v.parent],
      references: [testimonials.id],
      relationName: "parent",
    }),
  }),
);
export const relations_faqs = relations(faqs, () => ({}));
export const relations__faqs_v = relations(_faqs_v, ({ one }) => ({
  parent: one(faqs, {
    fields: [_faqs_v.parent],
    references: [faqs.id],
    relationName: "parent",
  }),
}));
export const relations_statistics = relations(statistics, () => ({}));
export const relations__statistics_v = relations(_statistics_v, ({ one }) => ({
  parent: one(statistics, {
    fields: [_statistics_v.parent],
    references: [statistics.id],
    relationName: "parent",
  }),
}));
export const relations_audit_log = relations(audit_log, ({ one }) => ({
  adminUser: one(users, {
    fields: [audit_log.adminUser],
    references: [users.id],
    relationName: "adminUser",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_jobs_log = relations(
  payload_jobs_log,
  ({ one }) => ({
    _parentID: one(payload_jobs, {
      fields: [payload_jobs_log._parentID],
      references: [payload_jobs.id],
      relationName: "log",
    }),
  }),
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: "log",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    documentsID: one(documents, {
      fields: [payload_locked_documents_rels.documentsID],
      references: [documents.id],
      relationName: "documents",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: "leads",
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: "testimonials",
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: "faqs",
    }),
    statisticsID: one(statistics, {
      fields: [payload_locked_documents_rels.statisticsID],
      references: [statistics.id],
      relationName: "statistics",
    }),
    "audit-logID": one(audit_log, {
      fields: [payload_locked_documents_rels["audit-logID"]],
      references: [audit_log.id],
      relationName: "audit-log",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_social = relations(site_social, ({ one }) => ({
  _parentID: one(site_settings, {
    fields: [site_social._parentID],
    references: [site_settings.id],
    relationName: "social",
  }),
}));
export const relations_site_legal_links = relations(
  site_legal_links,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_legal_links._parentID],
      references: [site_settings.id],
      relationName: "legalLinks",
    }),
  }),
);
export const relations_site_hero_ticker = relations(
  site_hero_ticker,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_hero_ticker._parentID],
      references: [site_settings.id],
      relationName: "heroTicker",
    }),
  }),
);
export const relations_site_settings_texts = relations(
  site_settings_texts,
  ({ one }) => ({
    parent: one(site_settings, {
      fields: [site_settings_texts.parent],
      references: [site_settings.id],
      relationName: "_texts",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    logo: one(media, {
      fields: [site_settings.logo],
      references: [media.id],
      relationName: "logo",
    }),
    social: many(site_social, {
      relationName: "social",
    }),
    legalLinks: many(site_legal_links, {
      relationName: "legalLinks",
    }),
    heroTicker: many(site_hero_ticker, {
      relationName: "heroTicker",
    }),
    masterPlan: one(documents, {
      fields: [site_settings.masterPlan],
      references: [documents.id],
      relationName: "masterPlan",
    }),
    _texts: many(site_settings_texts, {
      relationName: "_texts",
    }),
  }),
);
export const relations__site_social_v = relations(
  _site_social_v,
  ({ one }) => ({
    _parentID: one(_site_settings_v, {
      fields: [_site_social_v._parentID],
      references: [_site_settings_v.id],
      relationName: "version_social",
    }),
  }),
);
export const relations__site_legal_links_v = relations(
  _site_legal_links_v,
  ({ one }) => ({
    _parentID: one(_site_settings_v, {
      fields: [_site_legal_links_v._parentID],
      references: [_site_settings_v.id],
      relationName: "version_legalLinks",
    }),
  }),
);
export const relations__site_hero_ticker_v = relations(
  _site_hero_ticker_v,
  ({ one }) => ({
    _parentID: one(_site_settings_v, {
      fields: [_site_hero_ticker_v._parentID],
      references: [_site_settings_v.id],
      relationName: "version_heroTicker",
    }),
  }),
);
export const relations__site_settings_v_texts = relations(
  _site_settings_v_texts,
  ({ one }) => ({
    parent: one(_site_settings_v, {
      fields: [_site_settings_v_texts.parent],
      references: [_site_settings_v.id],
      relationName: "_texts",
    }),
  }),
);
export const relations__site_settings_v = relations(
  _site_settings_v,
  ({ one, many }) => ({
    version_logo: one(media, {
      fields: [_site_settings_v.version_logo],
      references: [media.id],
      relationName: "version_logo",
    }),
    version_social: many(_site_social_v, {
      relationName: "version_social",
    }),
    version_legalLinks: many(_site_legal_links_v, {
      relationName: "version_legalLinks",
    }),
    version_heroTicker: many(_site_hero_ticker_v, {
      relationName: "version_heroTicker",
    }),
    version_masterPlan: one(documents, {
      fields: [_site_settings_v.version_masterPlan],
      references: [documents.id],
      relationName: "version_masterPlan",
    }),
    _texts: many(_site_settings_v_texts, {
      relationName: "_texts",
    }),
  }),
);

type DatabaseSchema = {
  enum_admin_role: typeof enum_admin_role;
  enum_icon_name: typeof enum_icon_name;
  enum_project_category: typeof enum_project_category;
  enum_project_status: typeof enum_project_status;
  enum_projects_status: typeof enum_projects_status;
  enum__projects_v_version_status: typeof enum__projects_v_version_status;
  enum_lead_source: typeof enum_lead_source;
  enum_testimonials_status: typeof enum_testimonials_status;
  enum__testimonials_v_version_status: typeof enum__testimonials_v_version_status;
  enum_faqs_status: typeof enum_faqs_status;
  enum__faqs_v_version_status: typeof enum__faqs_v_version_status;
  enum_statistics_status: typeof enum_statistics_status;
  enum__statistics_v_version_status: typeof enum__statistics_v_version_status;
  enum_audit_action: typeof enum_audit_action;
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug;
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state;
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  media_texts: typeof media_texts;
  documents: typeof documents;
  documents_texts: typeof documents_texts;
  proj_stats: typeof proj_stats;
  proj_highlights: typeof proj_highlights;
  proj_approvals: typeof proj_approvals;
  proj_amenities: typeof proj_amenities;
  proj_loc_hl: typeof proj_loc_hl;
  proj_proximity: typeof proj_proximity;
  projects: typeof projects;
  projects_texts: typeof projects_texts;
  projects_rels: typeof projects_rels;
  _proj_stats_v: typeof _proj_stats_v;
  _proj_highlights_v: typeof _proj_highlights_v;
  _proj_approvals_v: typeof _proj_approvals_v;
  _proj_amenities_v: typeof _proj_amenities_v;
  _proj_loc_hl_v: typeof _proj_loc_hl_v;
  _proj_proximity_v: typeof _proj_proximity_v;
  _projects_v: typeof _projects_v;
  _projects_v_texts: typeof _projects_v_texts;
  _projects_v_rels: typeof _projects_v_rels;
  leads: typeof leads;
  testimonials: typeof testimonials;
  _testimonials_v: typeof _testimonials_v;
  faqs: typeof faqs;
  _faqs_v: typeof _faqs_v;
  statistics: typeof statistics;
  _statistics_v: typeof _statistics_v;
  audit_log: typeof audit_log;
  payload_kv: typeof payload_kv;
  payload_jobs_log: typeof payload_jobs_log;
  payload_jobs: typeof payload_jobs;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_social: typeof site_social;
  site_legal_links: typeof site_legal_links;
  site_hero_ticker: typeof site_hero_ticker;
  site_settings: typeof site_settings;
  site_settings_texts: typeof site_settings_texts;
  _site_social_v: typeof _site_social_v;
  _site_legal_links_v: typeof _site_legal_links_v;
  _site_hero_ticker_v: typeof _site_hero_ticker_v;
  _site_settings_v: typeof _site_settings_v;
  _site_settings_v_texts: typeof _site_settings_v_texts;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media_texts: typeof relations_media_texts;
  relations_media: typeof relations_media;
  relations_documents_texts: typeof relations_documents_texts;
  relations_documents: typeof relations_documents;
  relations_proj_stats: typeof relations_proj_stats;
  relations_proj_highlights: typeof relations_proj_highlights;
  relations_proj_approvals: typeof relations_proj_approvals;
  relations_proj_amenities: typeof relations_proj_amenities;
  relations_proj_loc_hl: typeof relations_proj_loc_hl;
  relations_proj_proximity: typeof relations_proj_proximity;
  relations_projects_texts: typeof relations_projects_texts;
  relations_projects_rels: typeof relations_projects_rels;
  relations_projects: typeof relations_projects;
  relations__proj_stats_v: typeof relations__proj_stats_v;
  relations__proj_highlights_v: typeof relations__proj_highlights_v;
  relations__proj_approvals_v: typeof relations__proj_approvals_v;
  relations__proj_amenities_v: typeof relations__proj_amenities_v;
  relations__proj_loc_hl_v: typeof relations__proj_loc_hl_v;
  relations__proj_proximity_v: typeof relations__proj_proximity_v;
  relations__projects_v_texts: typeof relations__projects_v_texts;
  relations__projects_v_rels: typeof relations__projects_v_rels;
  relations__projects_v: typeof relations__projects_v;
  relations_leads: typeof relations_leads;
  relations_testimonials: typeof relations_testimonials;
  relations__testimonials_v: typeof relations__testimonials_v;
  relations_faqs: typeof relations_faqs;
  relations__faqs_v: typeof relations__faqs_v;
  relations_statistics: typeof relations_statistics;
  relations__statistics_v: typeof relations__statistics_v;
  relations_audit_log: typeof relations_audit_log;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_jobs_log: typeof relations_payload_jobs_log;
  relations_payload_jobs: typeof relations_payload_jobs;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_social: typeof relations_site_social;
  relations_site_legal_links: typeof relations_site_legal_links;
  relations_site_hero_ticker: typeof relations_site_hero_ticker;
  relations_site_settings_texts: typeof relations_site_settings_texts;
  relations_site_settings: typeof relations_site_settings;
  relations__site_social_v: typeof relations__site_social_v;
  relations__site_legal_links_v: typeof relations__site_legal_links_v;
  relations__site_hero_ticker_v: typeof relations__site_hero_ticker_v;
  relations__site_settings_v_texts: typeof relations__site_settings_v_texts;
  relations__site_settings_v: typeof relations__site_settings_v;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
