/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    projects: Project;
    leads: Lead;
    testimonials: Testimonial;
    faqs: Faq;
    statistics: Statistic;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      usedAsCover: 'projects';
      usedInGallery: 'projects';
      usedAsLayout: 'projects';
      usedAsLocationMap: 'projects';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    statistics: StatisticsSelect<false> | StatisticsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      revalidatePaths: TaskRevalidatePaths;
      purgeLeadPii: TaskPurgeLeadPii;
      sweepDeletedMedia: TaskSweepDeletedMedia;
      watchdogFailedJobs: TaskWatchdogFailedJobs;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Administrator accounts. There is no public registration: an account can only be created here. Deactivate an account instead of deleting it — audit attribution must survive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  password?: string | null;
  /**
   * Shown in the audit log against everything this person changes.
   */
  name: string;
  role: 'admin';
  /**
   * Disable instead of deleting — audit attribution must survive. NOTE: unticking this closes the authorisation door on the next request, but does NOT end an existing session. To fully revoke access you must ALSO change this user’s password as an admin, which ends all of their sessions. See the deactivation runbook.
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'users';
}
/**
 * Photographs and artwork for the website. SVG files cannot be uploaded — export as PNG, JPEG or WebP.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for someone who cannot see it. If it carries no information of its own, tick "decorative" below and leave this blank.
   */
  alt: string;
  /**
   * Tick for purely decorative images. Screen readers will skip it. The logo and background plates are decorative.
   */
  isDecorative?: boolean | null;
  /**
   * Display only — never used as the storage key.
   */
  originalFilename?: string | null;
  uploadedBy?: (string | null) | User;
  supersededFilenames?: string[] | null;
  usedAsCover?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  usedInGallery?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  usedAsLayout?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  usedAsLocationMap?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The project catalogue. NOTE: until the website’s navigation is wired to this list, a newly published project appears at /projects, in the sitemap and at its own address, but NOT yet in the header dropdown or the footer column. Publishing a sixth project also requires a copy change on the homepage, which currently reads “Five layouts.”
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  _order?: string | null;
  name: string;
  /**
   * Shown on the card badge and used by the catalogue filter. One of four; a new category requires a frontend release.
   */
  category: 'Premium Villa Plots' | 'Farm Villa Plots' | 'Residential Plots' | 'Apartments';
  /**
   * Leave blank unless the brochure states one. No project has a status today — the card badge shows the category instead.
   */
  projectStatus?: ('Open for booking' | 'Nearing sell-out' | 'Completed' | 'Coming soon') | null;
  /**
   * The place as written on the brochure, e.g. "Gummadavelli, Jeedikal, Aler". Also shown in the enquiry form’s project list.
   */
  locality: string;
  /**
   * ONLY when the developer differs from the site’s own company name, so the catalogue attributes it separately instead of silently absorbing it. e.g. Sri Virinchi Infra Developers Pvt. Ltd.
   */
  developer?: string | null;
  /**
   * The short positioning line from the brochure cover.
   */
  tagline?: string | null;
  /**
   * Rendered as the LARGE HEADING on the detail page — not as a paragraph. Keep it to a sentence or two.
   */
  summary: string;
  /**
   * One entry per paragraph. Order is meaningful. Each paragraph must be unique — the website uses the text itself as a rendering key.
   */
  description: string[];
  /**
   * The total extent EXACTLY as printed, e.g. "6 Acres 22.50 Guntas". Never converted to a number — the unit and the precision are part of the claim.
   */
  area?: string | null;
  /**
   * Road widths and surfacing as printed, e.g. "60' & 30' wide BT roads".
   */
  roadDetails?: string | null;
  /**
   * The four-up figure strip. The grid is exactly four columns — use four, or none. Values are TEXT, exactly as printed ("6 Acres 22.50 Guntas", "DTCP & RERA", "100%").
   */
  stats?:
    | {
        label: string;
        /**
         * Text, never a number. "6 Acres 22.50 Guntas" and "DTCP & RERA" are both valid values.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The headline selling points. At least one is required — this section is not guarded in the page template.
   */
  highlights: {
    /**
     * Closed list. A new icon requires a frontend release.
     */
    icon:
      | 'arrowRight'
      | 'bank'
      | 'bolt'
      | 'briefcase'
      | 'bus'
      | 'check'
      | 'chevronDown'
      | 'chevronRight'
      | 'city'
      | 'close'
      | 'compass'
      | 'document'
      | 'download'
      | 'drain'
      | 'droplet'
      | 'external'
      | 'facebook'
      | 'fence'
      | 'hospital'
      | 'instagram'
      | 'key'
      | 'lamp'
      | 'mail'
      | 'mapPin'
      | 'menu'
      | 'phone'
      | 'plane'
      | 'road'
      | 'route'
      | 'ruler'
      | 'school'
      | 'shield'
      | 'shop'
      | 'star'
      | 'temple'
      | 'train'
      | 'tree'
      | 'wall'
      | 'whatsapp'
      | 'youtube'
      | 'zoomIn';
    title: string;
    /**
     * Optional. Most brochure highlights are one line.
     */
    body?: string | null;
    id?: string | null;
  }[];
  /**
   * ⚖️ LEGAL CLAIMS — these edits are audited. THE FIRST ITEM APPEARS IN THIS PROJECT’S SEARCH-RESULT DESCRIPTION, so reordering this list silently changes what Google shows.
   */
  approvals?:
    | {
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        title: string;
        /**
         * Optional. Most brochure highlights are one line.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Infrastructure and on-site facilities, kept separate from positioning.
   */
  amenities?:
    | {
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        title: string;
        /**
         * Optional. Most brochure highlights are one line.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Named surroundings. NO DISTANCE IS IMPLIED — if the brochure prints a distance, use Proximity instead.
   */
  locationHighlights?:
    | {
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        title: string;
        /**
         * Optional. Most brochure highlights are one line.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ⚖️ Only enter distances PRINTED ON THE BROCHURE. An unmeasured proximity claim is the one most likely to be challenged on a land page.
   */
  proximity?:
    | {
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        /**
         * e.g. "55 min" or "12 km" — as printed.
         */
        measure: string;
        place: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The card and hero image. Used at 4:3 on cards, 16:9 in the page hero, and as the social-sharing preview.
   */
  image: string | Media;
  /**
   * Site photography, plantation and cottage shots. Drag to reorder.
   */
  gallery?: (string | Media)[] | null;
  /**
   * The plot layout / master plan. Shown CONTAINED and zoomable — never cropped.
   */
  layoutImage?: (string | null) | Media;
  /**
   * The location map from the brochure. Shown contained, never cropped.
   */
  locationMap?: (string | null) | Media;
  /**
   * The project brochure as a PDF, chosen from Documents. Upload it under Media → Documents first, or use “Create New” here. ⚠️ NOT YET RENDERED ON THE WEBSITE: this field is editable now so brochures can be collected, but the public project page has no download link for it yet, so setting it changes nothing visible to a visitor.
   */
  brochure?: (string | null) | Document;
  /**
   * Overrides the shared call-to-action banner for this project only.
   */
  cta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Overrides the generated search-result title and description. Leave blank: the generated version is facts-only by construction, with no superlatives, because there is no field they could come from.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * The public web address for this project: /projects/<slug>. Generated from the name. LOCKED once the project has been published — changing it would break every link and search-engine listing that already points here.
   */
  slug: string;
  /**
   * Shows this project in the homepage Featured strip. That strip is a THREE-COLUMN grid — a fourth featured project leaves a ragged row.
   */
  featured?: boolean | null;
  /**
   * Set automatically when this project is first published. Drives the sitemap.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Downloadable PDFs — the master plan and brochures. PDF only, up to 25 MB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * Shown as the download link text, e.g. "Master plan (PDF)".
   */
  title: string;
  /**
   * Display only — never used as the storage key.
   */
  originalFilename?: string | null;
  uploadedBy?: (string | null) | User;
  supersededFilenames?: string[] | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Enquiries from the website contact form. A lead is a COMMERCIAL RECORD — archive it, never delete it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name: string;
  /**
   * As the visitor typed it.
   */
  phone: string;
  /**
   * E.164 form, used to spot duplicate enquiries.
   */
  phoneNormalised?: string | null;
  /**
   * Which project the visitor selected, if any.
   */
  projectSlug?: string | null;
  project?: (string | null) | Project;
  /**
   * The project name as it was when the enquiry arrived.
   */
  projectNameSnapshot?: string | null;
  message?: string | null;
  source: 'contact_form' | 'hero_pill' | 'whatsapp' | 'phone';
  /**
   * Which page the enquiry came from.
   */
  sourcePath?: string | null;
  /**
   * Implicit consent by submission: the privacy note is rendered next to the submit button. There is no separate consent checkbox on the form today.
   */
  consentGiven: boolean;
  /**
   * Housekeeping only — nothing on the dashboard depends on it.
   */
  isRead?: boolean | null;
  /**
   * Purged automatically after 90 days.
   */
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Client reviews for the homepage. A review CANNOT be published until you confirm the client actually gave it and agreed to it appearing on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  _order?: string | null;
  name: string;
  /**
   * e.g. "Plot owner, Sri City Aler Town".
   */
  role?: string | null;
  body: string;
  /**
   * Not currently displayed anywhere on the website.
   */
  rating?: number | null;
  /**
   * Tick ONLY if this client actually gave this review and agreed to it appearing on the website. Publishing is blocked until this is ticked — at the form, at the API and at the database.
   */
  consented: boolean;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Questions and answers shown on the homepage and the contact page. Drag to reorder — the first one is open by default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  _order?: string | null;
  /**
   * Must be unique — the website uses the question text as a rendering key.
   */
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The four-up figure strip on the homepage and the About page. The grid is exactly FOUR columns — publish four, or the row goes ragged. These figures are TYPED IN, never calculated: the database does not know how many plots have been handed over.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics".
 */
export interface Statistic {
  id: string;
  _order?: string | null;
  /**
   * e.g. "Plots handed over". Must be unique.
   */
  label: string;
  /**
   * TEXT, not a number. "250+", "100%" and "Immediate" are all valid. Typed in by hand — nothing derives this from the database.
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * A permanent record of every change made through this CMS, and of every sign-in. Read-only: nothing here can be edited or deleted, by anyone, through any interface.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: string;
  adminUser?: (string | null) | User;
  action:
    | 'create'
    | 'update'
    | 'publish'
    | 'unpublish'
    | 'delete'
    | 'restore'
    | 'login'
    | 'logout'
    | 'login_failed'
    | 'lockout'
    | 'password_change';
  entityType: string;
  entityId: string;
  /**
   * Before and after values for legally sensitive fields only — approvals, area, proximity and anything title-related. Never lead data.
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'revalidatePaths' | 'purgeLeadPii' | 'sweepDeletedMedia' | 'watchdogFailedJobs';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'revalidatePaths' | 'purgeLeadPii' | 'sweepDeletedMedia' | 'watchdogFailedJobs') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'statistics';
        value: string | Statistic;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  name?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isDecorative?: T;
  originalFilename?: T;
  uploadedBy?: T;
  supersededFilenames?: T;
  usedAsCover?: T;
  usedInGallery?: T;
  usedAsLayout?: T;
  usedAsLocationMap?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  originalFilename?: T;
  uploadedBy?: T;
  supersededFilenames?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  category?: T;
  projectStatus?: T;
  locality?: T;
  developer?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  area?: T;
  roadDetails?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  approvals?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  locationHighlights?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  proximity?:
    | T
    | {
        icon?: T;
        measure?: T;
        place?: T;
        id?: T;
      };
  image?: T;
  gallery?: T;
  layoutImage?: T;
  locationMap?: T;
  brochure?: T;
  cta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  phoneNormalised?: T;
  projectSlug?: T;
  project?: T;
  projectNameSnapshot?: T;
  message?: T;
  source?: T;
  sourcePath?: T;
  consentGiven?: T;
  isRead?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  body?: T;
  rating?: T;
  consented?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics_select".
 */
export interface StatisticsSelect<T extends boolean = true> {
  _order?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  adminUser?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  changes?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * These values appear on every page of the public website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * The public trading name. Renders in every page heading, every search-result title, the footer wordmark, the navigation bar and the sales notification email. ✅ RESOLVED 20 Sep 2026 (OQ-6): "SV Developers" — an owner decision, which supersedes the "SRR Developers Pvt. Ltd." that appears in the original brief.
   */
  name: string;
  /**
   * 🔶 STILL OPEN. The REGISTERED ENTITY name, used only in the copyright line — a DISTINCT FIELD with a distinct use, which is why resolving the public name above did not silently change this one. It currently mirrors the trading name because no registered entity name has been supplied. If the company is registered as "… Pvt. Ltd.", enter that exact string here; it is the only place the footer copyright reads from.
   */
  legalName: string;
  tagline?: string | null;
  description?: string | null;
  /**
   * The public website address, e.g. https://www.svdevelopers.in — no trailing slash. This feeds every canonical link, every social-sharing tag and every sitemap entry.
   */
  url: string;
  /**
   * Should be a transparent PNG. SVG cannot be uploaded — see the media library.
   */
  logo?: (string | null) | Media;
  /**
   * Used for the mailto: link in the footer and on the contact page.
   */
  email: string;
  /**
   * Displayed exactly as typed, and used for the click-to-call link.
   */
  phone: string;
  /**
   * ⚠️ THREE CONSEQUENCES, all of which fire on the first day of real content. (1) Setting a real value CHANGES THE HOMEPAGE HERO: the enquiry pill stops routing to /contact and opens WhatsApp directly. (2) Those enquiries are then NOT RECORDED ANYWHERE — no lead row is created. (3) The contact page currently passes this value as a raw link and will 404 until that is fixed. Digits only, country code first, no + and no spaces.
   */
  whatsapp: string;
  /**
   * One line per entry, in the order they should be printed. Rendered as three stacked lines — NOT a free-text block.
   */
  address: string[];
  /**
   * A Google Maps link to the office.
   */
  mapUrl?: string | null;
  officeHours?: string | null;
  social?:
    | {
        label: string;
        href: string;
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        id?: string | null;
      }[]
    | null;
  /**
   * ⚖️ A PRIVACY POLICY IS LEGALLY REQUIRED once the website collects a name and phone number. The enquiry form is switched off in production until a real privacy URL is configured.
   */
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ⚖️ THIS IS THE CONSENT ARTEFACT. It is rendered next to the submit button and is the promise the business makes about how the number will be used. It must stay truthful to actual data use — if leads are ever sent to a third party, this sentence has to change first.
   */
  formNote?: string | null;
  /**
   * The closing call-to-action banner. NOTE: this is {title, body}; the PER-PROJECT override is {title, description}. They are different fields and are not interchangeable.
   */
  cta?: {
    title?: string | null;
    body?: string | null;
  };
  /**
   * The scrolling claims under the homepage headline. Each line must be unique.
   */
  heroTicker?:
    | {
        /**
         * Closed list. A new icon requires a frontend release.
         */
        icon:
          | 'arrowRight'
          | 'bank'
          | 'bolt'
          | 'briefcase'
          | 'bus'
          | 'check'
          | 'chevronDown'
          | 'chevronRight'
          | 'city'
          | 'close'
          | 'compass'
          | 'document'
          | 'download'
          | 'drain'
          | 'droplet'
          | 'external'
          | 'facebook'
          | 'fence'
          | 'hospital'
          | 'instagram'
          | 'key'
          | 'lamp'
          | 'mail'
          | 'mapPin'
          | 'menu'
          | 'phone'
          | 'plane'
          | 'road'
          | 'route'
          | 'ruler'
          | 'school'
          | 'shield'
          | 'shop'
          | 'star'
          | 'temple'
          | 'train'
          | 'tree'
          | 'wall'
          | 'whatsapp'
          | 'youtube'
          | 'zoomIn';
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The master-plan PDF offered for download on /master-plan.
   */
  masterPlan?: (string | null) | Document;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  description?: T;
  url?: T;
  logo?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  mapUrl?: T;
  officeHours?: T;
  social?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  formNote?: T;
  cta?:
    | T
    | {
        title?: T;
        body?: T;
      };
  heroTicker?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  masterPlan?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRevalidatePaths".
 */
export interface TaskRevalidatePaths {
  input: {
    paths: string[];
    tags?: string[] | null;
  };
  output: {
    revalidated: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurgeLeadPii".
 */
export interface TaskPurgeLeadPii {
  input?: unknown;
  output: {
    purged: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSweepDeletedMedia".
 */
export interface TaskSweepDeletedMedia {
  input?: unknown;
  output: {
    swept: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskWatchdogFailedJobs".
 */
export interface TaskWatchdogFailedJobs {
  input?: unknown;
  output: {
    alerts: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}